### ISSUE TITLE
ModuleNotFoundError: No module named 'nvstrings' (rapids-colab.ipynb)

### ISSUE THREAD

**Issue by gumdropsteve** [rapidsai/notebooks-extended#104]
#### Error
`ModuleNotFoundError: No module named 'nvstrings'` 
#### To Reproduce 
Run [cuDF cell](https://colab.research.google.com/drive/1XTKHiIcvyL5nuldx0HSL_dUa8yopzy_Y#scrollTo=EwaJSKuswsNi&line=5&uniqifier=1) after executing prior cells from rapids-colab.ipynb [example notebook](https://colab.research.google.com/drive/1XTKHiIcvyL5nuldx0HSL_dUa8yopzy_Y#forceEdit=true&offline=true&sandboxMode=true) in Google Colab. 

Notebook linked under "[Get Started](https://rapids.ai/start.html)" on rapids.ai. 

#### Code
```
import nvstrings, nvcategory, cudf
import io, requests

# download CSV file from GitHub
url="https://github.com/plotly/datasets/raw/master/tips.csv"
content = requests.get(url).content.decode('utf-8')

# read CSV from memory
tips_df = cudf.read_csv(io.StringIO(content))
tips_df['tip_percentage'] = tips_df['tip']/tips_df['total_bill']*100

# display average tip by dining party size
print(tips_df.groupby('size').tip_percentage.mean())
```

#### Temp Solution
Re-run [Setup cell](https://colab.research.google.com/drive/1XTKHiIcvyL5nuldx0HSL_dUa8yopzy_Y#scrollTo=m0jdXBRiDSzj); issue is always resolved. 

#### Full Output
```
---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-4-77b6558ae5dc> in <module>()
----> 1 import nvstrings, nvcategory, cudf
      2 import io, requests
      3 
      4 # download CSV file from GitHub
      5 url="https://github.com/plotly/datasets/raw/master/tips.csv"

ModuleNotFoundError: No module named 'nvstrings'


---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by taureandyernv** [comment]
@gumdropsteve , we pushed a new start up script today.  Check out https://github.com/rapidsai/notebooks-extended/pull/110 and the new script to see if it solves you prroblem :)

**Comment by gumdropsteve** [comment]
Yes, this solves the issue. 

It does take a bit longer (than the old setup script) to install everything but the new script from #110 worked on the first time every time (tested 5 times). 

New script does not seem to be in [Example Google Colab](https://colab.research.google.com/drive/1XTKHiIcvyL5nuldx0HSL_dUa8yopzy_Y#forceEdit=true&offline=true&sandboxMode=true) yet so I'll leave this issue open?

-- Thank you

**Comment by gumdropsteve** [comment]
Yes @taureandyernv , this solves the setup issue. It does take a bit longer (than the old setup script) to install everything but the new script from #110 worked on the first time every time (tested 5 times). 

New script does not seem to be in [Example Google Colab](https://colab.research.google.com/drive/1XTKHiIcvyL5nuldx0HSL_dUa8yopzy_Y#forceEdit=true&offline=true&sandboxMode=true) yet though, so I'll leave this issue open?

-- Thank you
