### ISSUE TITLE
spark_rapids_pca_demo.ipynb Using Spark to just read a dataframe is redundant

### ISSUE THREAD

**Issue by pklemenkov** [rapidsai/notebooks-extended#31]
Please rename the notebook and get rid of Spark. `pandas.read_csv` will do the same job and not confuse users.

**Comment by krajendrannv** [comment]
submitted a PR to fix this.
https://github.com/rapidsai/notebooks-extended/pull/32

**Comment by taureandyernv** [comment]
We thought so too so we've updated the notebook, so things should be all smiles now.
