### ISSUE TITLE
Error building the notebooks-extended: ADD failed: stat /var/lib/docker/tmp/docker-builder566067138/cpu_comparisons: no such file or directory

### ISSUE THREAD

**Issue by vilmara** [rapidsai/notebooks-extended#41]
Hi, I am getting the below error building the notebooks-extended, some tip on how to fix it?, see below

`docker build -t notebooks-extended .`

**error:**
```
Step 9/13 : ADD cpu_comparisons /rapids/notebooks/extended/cpu_comparisons
ADD failed: stat /var/lib/docker/tmp/docker-builder566067138/cpu_comparisons: no such file or directory
```

**Comment by taureandyernv** [comment]
@vilmara , please follow our readme example here: https://github.com/rapidsai/notebooks-extended/blob/master/BUILD.md.  It is much easier and faster than doing a docker build.  be sure to git pull the notebook-extended repo to your the folder of your choice, and use that path as your volume mount, as per the instructions

**Comment by vilmara** [comment]
thanks @taureandyernv, issue solved with your instructions, I have to update also the path from `/folder/of/your/choice/:notebooks/extended` to  `/folder/of/your/choice/:/rapids/notebooks/extended/` to make it work
