### ISSUE TITLE
how to run the performance testing cpu vs gpu

### ISSUE THREAD

**Issue by vilmara** [rapidsai/notebooks-extended#42]
hi all, what is the sample code to run the benchmark as shown in this picture?
![Screenshot (72)](https://user-images.githubusercontent.com/30601934/57811225-56816680-772f-11e9-8eb4-bd2dd6d75032.png)

**Comment by taureandyernv** [comment]
@vilmara , will will get back to you on that, but do you have access to a DGX-x to match that performance?  Less performent GPU systems will be...well...slower :)

**Comment by vilmara** [comment]
Hi @taureandyernv thanks for your reply, Yes I do have access to a DGX-x, but also I want to run this benchmark using a system in distributed mode connecting 2 servers with 4x-V100 gpus each (total 8 GPUS).  Could you please assist on how to run the above performance testing cpu vs gpu, and also on how to configure RAPIDS to work in distributed mode?
