### ISSUE TITLE
[DOC] Lorem ipsum in 01_Introduction_to_RAPIDS.ipynb notebook

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/notebooks-extended#44]
Hi,

At the bottom of the **01_Introduction_to_RAPIDS.ipynb** jupyter notebook, it can be seen a Lorem ipsom paragraph.

![image](https://user-images.githubusercontent.com/26169771/57831775-54aeb600-77b6-11e9-9874-3f87b65f7b28.png)

I think that content should be updated or removed.

Regards,
Miguel

**Comment by taureandyernv** [comment]
Closed with https://github.com/rapidsai/notebooks-extended/pull/47
