### ISSUE TITLE
[BUG] Incorrect path at Getting_started_with_CUDF.ipynb notebook

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/notebooks-extended#45]
Hi,

I have git cloned this project, and when trying to run the cell #4 of **Gestting_started_with_CUDF.ipynb** notebook, the following error is displayed:

![image](https://user-images.githubusercontent.com/26169771/57832016-e0c0dd80-77b6-11e9-89d9-0eacc245bd66.png)

I would suggest to use relative path to the dataset, something as follows:

```
# read data from csv file into pandas dataframe
df = pd.read_csv('../../data/ipums/ipums_easy.csv')
```

Hope it helps.

Regards,
Miguel

**Comment by taureandyernv** [comment]
Closed with https://github.com/rapidsai/notebooks-extended/pull/47.  Thanks for the test, miguel!
