### ISSUE TITLE
[BUG] Unclear comment on Getting_started_with_cuDF.ipynb notebook

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/notebooks-extended#46]
Hi, 

**Getting_started_with_cuDF.ipynb notebook** jupyter notebook mentions the following:

> Machine learning models won't take as input strings as so we need to convert each column and its string representations to a numerical representation.

That paragraph could make the reader think that the columns that are going to be treated in the next cell are string columns when they are actually int64 columns containing categorical values.

![image](https://user-images.githubusercontent.com/26169771/57835951-f8509400-77bf-11e9-8b4e-4e0517e40c89.png)

I would suggest changing the content of **ipums_easy.csv** to force those columns to be read as string columns, instead of int64 columns.

Regards,
Miguel

**Comment by taureandyernv** [comment]
Closed with https://github.com/rapidsai/notebooks-extended/pull/47.  Thanks Miguel!
