### ISSUE TITLE
[FEA] Multi-Node / Multi-GPU Dask-XGBoost sample 

### ISSUE THREAD

**Issue by vilmara** [rapidsai/notebooks-extended#51]
Hi all, is there a sample that shows how to run Dask-XGBoost with Multi-Node / Multi-GPU configuration?

**Comment by taureandyernv** [comment]
One is in the works and we will have one up shortly.

**Comment by vilmara** [comment]
hi @taureandyernv / @randerzander , could you please update with the status of this enhancement?.  May I know what approach are you taking?. Are you using Dask distributed across clusters? https://docs.dask.org/en/latest/setup.html

**Comment by paulhendricks** [comment]
Hi @vilmara - Can you take a look at this notebook?

https://github.com/rapidsai/notebooks-extended/blob/master/beginner/tutorial/07_Introduction_to_Dask_XGBoost.ipynb

That notebook shows how to work with Dask XGBoost for Single Node Multi GPU. This workflow can be modified to extend to Multi Node / Multi GPU.

**Comment by vilmara** [comment]
hi @paulhendricks / @taureandyernv, thanks for your comments. I have found an usseful example at **Running a benchmark with RAPIDS and Dask with Slurm on bare metal. Example Distributed Multi-Node Mode**
https://github.com/NVIDIA/deepops/tree/master/examples/slurm-bare-metal-dask-rapids
