### ISSUE TITLE
ModuleNotFoundError: No module named 'ipyvolume' (RAPIDS Demo End-To-End ML Workflow)

### ISSUE THREAD

**Issue by vilmara** [rapidsai/notebooks-extended#52]
Hi all, the RAPIDS Demo End-To-End ML Workflow is throwing the following error, could you help please?:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-b0bb00575e05> in <module>
     11 from numba import cuda
     12 
---> 13 import ipyvolume as ipv
     14 import matplotlib.pyplot as plt
     15 from fig_helpers import *

ModuleNotFoundError: No module named 'ipyvolume'
```

**Comment by vilmara** [comment]
I fixed the error `ModuleNotFoundError: No module named 'ipyvolume'` by installing the below packages:
```
pip install ipywidgets~=7.4.0
pip install ipyvolume
```
But now I got this new error:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-b0bb00575e05> in <module>
     13 import ipyvolume as ipv
     14 import matplotlib.pyplot as plt
---> 15 from fig_helpers import *
     16 import time

ModuleNotFoundError: No module named 'fig_helpers'
```

**Comment by taureandyernv** [comment]
@Vilmara, i was going to update you with the fix once i figured out "fig_helpers"...which i did.  I've contacted the notebook maker and asked him to package it with matplotlib, which I believe he did.  Stay tuned for an update, as i verify and run tests :)

**Comment by taureandyernv** [comment]
@vilmara , @miroenev updated the notebook.  Can you please see if this resolves your issue so i can close this?  Thanks!

**Comment by vilmara** [comment]
@taureandyernv / @miroenev , notebook working. Thanks!
