### ISSUE TITLE
[BUG] Memory issue running mortgage notebook on RTX8000

### ISSUE THREAD

**Issue by alawami** [rapidsai/notebooks-extended#59]
Running the mortgage notebook:

https://github.com/rapidsai/notebooks-extended/blob/master/advanced/E2E/mortgage/mortgage_e2e.ipynb

On NGC containers:

0.7-cuda10.0-devel-ubuntu18.04-gcc7-py3.6
and
0.6-cuda10.0-devel-ubuntu18.04-gcc7-py3.6

On dual RTX8000 cards, I can do 8 parts of the data. However, when I try running on more parts and monitor memory usage on nvidia-smi it reaches half the memory usage and then breaks. Memory usage would go to near zero and it will stall and nothing would happen.

**Comment by taureandyernv** [comment]
@alawami, it is interesting that it reaches half memory usage and then breaks.  Is it half total GPU memory usage or just half of one card?  If half of total, probably only one GPU is in use and it fulled up all the memory.  Otherwise, it's a different problem.  Please let me know!

**Comment by alawami** [comment]
@taureandyernv using nvidia-smi I can see it using half the memory on each card.

**Comment by datametrician** [comment]
You can't do more than 8 parts on dual RTX8000. I imagine during the join stage where it needs 2x memory it's hitting that prior to reporting it in NVIDIA-smi and crashing/stalling. Given that you're only supposed to run max 4 parts per RTX8000, I'm going to close this issue.
