### ISSUE TITLE
Error while trying to run the code for Photometric LSST Astronomical Time-Series Classification Challenge (PLAsTiCC)

### ISSUE THREAD

**Issue by vp2527** [rapidsai/notebooks-extended#69]
Wanted to study the performance of GPUs compared to that of the CPUs. Found the code for the kaggle competition Photometric LSST Astronomical Time-Series Classification Challenge (PLAsTiCC). It's path is notebooks-extended/expert/E2E/plasticc/notebooks/rapids_lsst_full_demo.ipynb

I downloaded the dataset and even loaded them into their respective data frames. Received the following error while trying to run : ETL part 1 with 100x speedup

`
step = 'ETL part1'
start = time.time()
aggs = {'flux':['skew']}
test_gd = cudf_groupby_aggs(test_gd,group_id_col='object_id',aggs=aggs)
train_gd = cudf_groupby_aggs(train_gd,group_id_col='object_id',aggs=aggs)
GPU_RUN_TIME[step] = time.time() - start`

ERROR : 

`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<timed exec> in <module>

/rapids/notebooks/vishnupriya/notebooks-extended/expert/E2E/plasticc/notebooks/cudf_workaround.py in cudf_groupby_aggs(df, group_id_col, aggs)
    339         for func in funcs:
    340             if dg is None:
--> 341                 dg = cudf_groupby_agg(df,group_id_col,col,func)
    342             else:
    343                 tmp = cudf_groupby_agg(df,group_id_col,col,func)

/rapids/notebooks/vishnupriya/notebooks-extended/expert/E2E/plasticc/notebooks/cudf_workaround.py in cudf_groupby_agg(df, idcol, col, func_name)
    313     dg = df.groupby(idcol).agg({outcol:'mean'})
    314     df.drop_column(outcol)
--> 315     dg = rename_col(dg,'mean_%s'%outcol,outcol)
    316     #meancol = 'mean_%s'%outcol
    317     #dg[outcol] = dg[meancol]

/rapids/notebooks/vishnupriya/notebooks-extended/expert/E2E/plasticc/notebooks/cudf_workaround.py in rename_col(df, oldcol, newcol)
      6 
      7 def rename_col(df, oldcol, newcol):
----> 8     df[newcol] = df[oldcol]
      9     df.drop_column(oldcol)
     10     return df

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/dataframe.py in __getitem__(self, arg)
    221             return self.columns._get_column_major(self, arg)
    222         if isinstance(arg, (str, numbers.Number)) or isinstance(arg, tuple):
--> 223             s = self._cols[arg]
    224             s.name = arg
    225             s.index = self.index

KeyError: 'mean_skew_flux'
`

Tried looking at the source code at cudf_workaround.py in the same directory. But couldn't figure out what was causing this error.

**Comment by taureandyernv** [comment]
@vp2527, I just pushed in Jiwei's PR https://github.com/rapidsai/notebooks-extended/pull/73 that fixed it.  You can now find the Kaggle notebooks at https://github.com/rapidsai/notebooks-extended/tree/master/competition_notebooks/kaggle.  Can you verify that it now works?

**Comment by daxiongshu** [comment]
Thank you. @vp2527 It runs with cudf 0.7. I'm happy to help with any issues.

**Comment by vp2527** [comment]
It runs perfectly now. Thank You!

**Comment by taureandyernv** [comment]
awesome!
