### ISSUE TITLE
cudf dataframe creation error

### ISSUE THREAD

**Issue by clahlou** [rapidsai/notebooks-extended#79]
<img width="1002" alt="Screen Shot 2019-06-19 at 12 48 16 PM" src="https://user-images.githubusercontent.com/46354193/59784678-05feab00-9291-11e9-9b9e-bcbabcd6e23e.png">

From running "Getting_Started_with_cuDF" notebook

**Comment by taureandyernv** [comment]
Hey @clahlou , I just ran it and received no errors.  Can you copy and paste your entire error message?  Also, what GPU are you using?

**Comment by clahlou** [comment]
I was running on a DGX-1 server. Not sure why but it works now...
